### ISSUE TITLE
question with dataset preprocessor

### ISSUE THREAD

**Issue by Jiawei0o0** [SaverioVad/HAD_Net#2]
Thanks for your great work. I am working on the Brats2018 dataset. Can I apply 'data_preprocessor.py' on the Brats2018 directly?

**Comment by SaverioVad** [comment]
While I have never tried myself, I do not see a reason why the pre-processor would not work on the BraTS 2018 data. However, one would likely need to change the way the script traverses the data directories if the layout differs between the 2019 and 2018 data. Hope this helps.
